### ISSUE TITLE
Full-network eavesdrop

### ISSUE THREAD

**Issue by mrbluecoat** [rafael-santiago/macgonuts#18]
Cool project - puns galore! 

Quick question: is `eavesdrop` the right tool to monitor traffic between a target and the internet or should I `spoof` and use another tool for that? Ideally I'd like to monitor all network traffic flowing through port 80 after using `spoof` to become the gateway. 

Since I manage the test lab, if I can install a certificate on the targets does your tool support TLS MITM or should I also use another tool for that?

**Comment by rafael-santiago** [comment]
Hi!

>Cool project - puns galore!

Thank you! The idea is to have a powerful exploitation tool but without taking it so seriously, I believe that it is against the grain because in `IT` field nowadays, people are becoming pretty bore. You can be a specialist in something without being a robot, without taking yourself so seriously, I believe. It makes the whole stuff more human driven. What in `AI` times is precious!

>Quick question: is eavesdrop the right tool to monitor traffic between a target and the internet or should I spoof and use another tool for that? Ideally I'd like to monitor all network traffic flowing through port 80 after using spoof to become the gateway.

When I wrote `eavesdrop` mode, I was thinking about active sniffing. So in this scenario you have a `LAN` segmented into `bridges` (maybe kind oldish nowadays, but it still exists) or with "multi-port hubs" a.k.a `switches`. The issue with this kind of network environment is that passive sniffing (by putting your interface in promisc mode and watch the whole traffic that hits your network stack) will not work on with the whole `LAN`, because all traffic that you will be able to be in touch is only the packets inside your segment, it is passive sniffing. So sniffing packets in segmented `LAN`s are clumsy if you do not have an active sniffer, because you need to be (phisically [in real, real `3D`] in the same network segment of your targets). 

So `eavesdrop` is about active sniffing. Even if your targets are in other `LAN` segments you will be able to get the packets from their channel. It is totally driven by interception or monitoring because it is about: spoofing, sniffing, redirecting, filtering and displaying relevant data or still exporting it to `PCAP` file to poke it later. So it is about spoofing with eaveasdropping intentions. In other words it was implemented by automating a bunch of things that you would need to do on your own when using just a raw toy-like spoofing script. It must have be counterparts in order to do not interrupt the communication and promoting a successful attack simulation.

If you want to get the Internet packets from a local target, I believe that `eavesdrop` is the more indicated blade of your spoofing swiss army knife to use 😉 . In this case even not being in different network segments I believe it would work. In this case your targets would be the local node and the network gateway.

Now the performance could be compromised if the traffic become intense. Notice that you are messing with/deceiving the network gateway. You need to take it into consideration.

Using `spoof` mode it would only do the spoofing part (`L2`) (that `eavesdrop` under the hood also does) but the whole interception part, conversion to pcap it would be up to the other tools.

>Since I manage the test lab, if I can install a certificate on the targets does your tool support TLS MITM or should I also use another tool for that?

Since I finished the first release I have been ruming new modes in my mind, I already thought about implementing a more automated way of `TLS MITM` but it has a bunch of operational gaps to overcome to deliver a fully functional tool. Until now `macgonuts` does not feature a `decryption` facility for it. Anyway the `eavesdrop` mode is able to generate a `PCAP` so you would be able to redirect it to some tools that analyses it, I meaning tools such as `tcpdump` or `wireshark` etc.

If you have ideas of how to integrate `TLS MITM` in `macgonuts` let's talk about. Trying to have a well-defined list of things to implement to deliver a useful tool. I accept suggestions.
